need to constrain aws provider to 3.12.0
With current version (3.18.0) getting error on plan:

Error: Provider produced inconsistent final plan

When expanding the plan for module.ecsadminer.aws_ecs_service.service to
include new values learned so far during apply, provider
"registry.terraform.io/-/aws" produced an invalid new value for
.wait_for_steady_state: was cty.False, but now null.

This is a bug in the provider, which should be reported in the provider's own issue tracker.